//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phone_Store_Management.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warranty
    {
        public int WarrantyID { get; set; }
        public string PhoneNumber { get; set; }
        public int ProductID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
        public virtual Product Product { get; set; }
    }
}
